name: pezhvak
description: "pezhvak main web page"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get: ^4.6.6
  get_storage: ^2.1.1
  blurbox: ^0.0.3
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic

  #   - family: Example
  #     fonts:
  #       - asset: assets/fonts/
  #       - asset: assets/fonts/
  #         